config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from phandler.core.views import HelpView, HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("help/", HelpView.as_view(), name="help"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("phandler.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("records/", include("phandler.records.urls", namespace="records")),
    path(
        "appointments/", include("phandler.appointments.urls", namespace="appointments")
    )
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

phandler/appointments/urls.py
from django.urls import path

from . import views

app_name = "appointments"
urlpatterns = [
    path("", views.AppointmentListView.as_view(), name="list"),
    path("create/", views.AppointmentCreateView.as_view(), name="create"),
]

phandler/records/urls.py
from django.urls import path

from . import views

app_name = "records"
urlpatterns = [
    path("doctor-create/", views.DoctorCreateView.as_view(), name="doctor_create"),
    path("patient-create/", views.PatientCreateView.as_view(), name="patient_create"),
    path("record-list/", views.RecordListView.as_view(), name="list"),
    path("record-detail/<int:pk>/", views.RecordDetailView.as_view(), name="detail"),
    path("patient-list/", views.PatientListView.as_view(), name="patient_list"),
    path("doctor-list/", views.DoctorListView.as_view(), name="doctor_list"),
]

phandler/users/urls.py
from django.urls import path

from phandler.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

phandler/appointments/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from djmoney.models.fields import MoneyField
from model_utils.models import TimeStampedModel


class Appointment(TimeStampedModel):
    record = models.ForeignKey(
        "records.Record", on_delete=models.CASCADE, related_name="history"
    )
    doctor = models.ForeignKey("records.Doctor", on_delete=models.CASCADE)
    sickness = models.CharField(max_length=255)
    prescriptions = ArrayField(models.CharField(max_length=30), default=list)
    cost = MoneyField(max_digits=14, decimal_places=2, default_currency="XOF")
    date = models.DateTimeField()
    accepted = models.BooleanField(default=True)
    duration = models.PositiveSmallIntegerField(
        default=30, help_text="Duration in minutes"
    )

    def __str__(self):
        return f"{self.record.patient} - {self.doctor} - {self.date}"

phandler/records/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel
from phonenumber_field.modelfields import PhoneNumberField


class Person(TimeStampedModel):
    class Gender(models.TextChoices):
        Male = "Male", _("Male")
        Female = "Female", _("Female")

    name = models.CharField(max_length=255)
    gender = models.CharField(choices=Gender.choices, max_length=6)
    email = models.EmailField(blank=True)
    phone = PhoneNumberField()
    id_card_number = models.CharField(max_length=30, unique=True)
    address = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Patient(Person):
    age = models.PositiveSmallIntegerField()
    allergies = ArrayField(models.CharField(max_length=30), default=list, blank=True)

    def allergies_str(self) -> str:
        return ", ".join(self.allergies)


class Doctor(Person):
    specialities = ArrayField(models.CharField(max_length=30), default=list)


class Record(TimeStampedModel):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.patient} - Medical record"

    def get_absolute_url(self) -> str:
        return reverse("records:detail", kwargs={"pk": self.pk})

phandler/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for phandler."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

phandler/appointments/forms.py
from datetime import timedelta

from django import forms

from .models import Appointment


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            "record",
            "doctor",
            "sickness",
            "prescriptions",
            "cost",
            "accepted",
            "duration",
            "date",
        ]
        widgets = {
            "date": forms.DateTimeInput(attrs={"placeholder": "DD/MM/YYYY HH:MM"})
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        date = cleaned_data["date"]
        doctor = self.cleaned_data["doctor"]
        try:
            aps = Appointment.objects.filter(doctor=doctor, date__date=date)
        except Appointment.DoesNotExist:
            pass
        else:
            for ap in aps:
                ap_end = ap.date + timedelta(minutes=ap.duration)
                if ap_end >= date:
                    raise forms.ValidationError(
                        f"Doctor {doctor} have another appointment on "
                        f"the {ap.date} for a duration of {ap.duration}"
                    )
        return cleaned_data

phandler/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

phandler/appointments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django_filters.views import FilterView
from django_tables2.export.views import ExportMixin
from django_tables2.views import SingleTableMixin

from .filters import AppointmentFilter
from .forms import AppointmentForm
from .models import Appointment
from .tables import AppointmentTable


class AppointmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = AppointmentForm
    template_name = "appointments/create.html"
    success_message = "New appointments crated"
    success_url = reverse_lazy("appointments:list")


class AppointmentListView(
    LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView
):
    queryset = Appointment.objects.all().order_by("-date")
    filterset_class = AppointmentFilter
    template_name = "appointments/list.html"
    table_class = AppointmentTable

phandler/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "pages/home.html"


class HelpView(LoginRequiredMixin, TemplateView):
    template_name = "pages/help.html"

phandler/records/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from django_filters.views import FilterView
from django_tables2.export.views import ExportMixin
from django_tables2.views import SingleTableMixin

from phandler.appointments.tables import AppointmentTable

from .filters import DoctorFilter, PatientFilter, RecordFilter
from .models import Doctor, Patient, Record
from .tables import DoctorTable, PatientTable


class PatientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Patient
    fields = [
        "name",
        "id_card_number",
        "gender",
        "age",
        "email",
        "address",
        "phone",
        "allergies",
    ]
    template_name = "records/patient_create.html"
    success_message = "Patient created"
    success_url = reverse_lazy("records:patient_list")


class DoctorCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Doctor
    fields = [
        "name",
        "id_card_number",
        "gender",
        "email",
        "address",
        "phone",
        "specialities",
    ]
    template_name = "records/doctor_create.html"
    success_message = "Doctor created"
    success_url = reverse_lazy("records:doctor_list")


class DoctorListView(LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView):
    table_class = DoctorTable
    filterset_class = DoctorFilter
    queryset = Doctor.objects.all().order_by("-created")
    template_name = "records/doctor_list.html"
    context_object_name = "doctors"


class PatientListView(LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView):
    table_class = PatientTable
    filterset_class = PatientFilter
    queryset = Patient.objects.all().order_by("-created")
    template_name = "records/patient_list.html"
    context_object_name = "patients"


class RecordListView(LoginRequiredMixin, FilterView):
    queryset = Record.objects.all().order_by("-created")
    template_name = "records/list.html"
    filterset_class = RecordFilter
    context_object_name = "records"
    paginate_by = 12


class RecordDetailView(LoginRequiredMixin, SingleTableMixin, DetailView):
    model = Record
    context_object_name = "record"
    template_name = "records/detail.html"
    table_class = AppointmentTable

    def get_table_data(self):
        return self.object.history.all().order_by("-date")

phandler/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

phandler/templates/layouts/admin.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <header class="app-header fixed-top">
    <div class="app-header-inner">
      <div class="container-fluid py-2">
        <div class="app-header-content">
          <div class="row justify-content-between align-items-center">
            <div class="col-auto">
              <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>
                  Menu</title>
                  <path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2"
                        d="M4 7h22M4 15h22M4 23h22"></path>
                </svg>
              </a>
            </div><!--//col-->
            <div class="search-mobile-trigger d-sm-none col">
              <i class="search-mobile-trigger-icon fas fa-search"></i>
            </div><!--//col-->
            <div class="app-search-box col">
              <form class="app-search-form">
                <input type="text" placeholder="Search..." name="search" class="form-control search-input">
                <button type="submit" class="btn search-btn btn-primary" value="Search">
                  <i class="fas fa-search"></i></button>
              </form>
            </div><!--//app-search-box-->

            <div class="app-utilities col-auto">
              <div class="app-utility-item app-user-dropdown dropdown">
                <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                   aria-expanded="false"><img src="https://avatars.dicebear.com/api/human/{{ user.username }}.svg"
                                              alt="user profile"></a>
                <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
                  <li><a class="dropdown-item" href="{% url 'users:detail' user.username %}">Account</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a></li>
                </ul>
              </div><!--//app-user-dropdown-->
            </div><!--//app-utilities-->
          </div><!--//row-->
        </div><!--//app-header-content-->
      </div><!--//container-fluid-->
    </div><!--//app-header-inner-->
    <div id="app-sidepanel" class="app-sidepanel sidepanel-visible">
      <div id="sidepanel-drop" class="sidepanel-drop"></div>
      <div class="sidepanel-inner d-flex flex-column">
        <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">×</a>
        <div class="app-branding">
          <a class="app-logo" href="{% url 'home' %}">
            <img class="logo-icon me-2" src="{% static 'images/app-logo.svg' %}" alt="logo"><span
            class="logo-text">PHandler</span></a>

        </div><!--//app-branding-->

        <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
          <ul class="app-menu list-unstyled accordion" id="menu-accordion">
            <li class="nav-item">
              <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
              <a class="nav-link" href="{% url 'home' %}">
						        <span class="nav-icon">
						        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
		  <path fill-rule="evenodd"
            d="M7.646 1.146a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5H9.5a.5.5 0 0 1-.5-.5v-4H7v4a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6zM2.5 7.707V14H6v-4a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4h3.5V7.707L8 2.207l-5.5 5.5z"></path>
		  <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"></path>
		</svg>
						         </span>
                <span class="nav-link-text">Overview</span>
              </a><!--//nav-link-->
            </li><!--//nav-item-->
            <li class="nav-item">
              <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
              <a class="nav-link" href="{% url "records:list" %}">
						        <span class="nav-icon">
						        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-folder" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
  <path
    d="M9.828 4a3 3 0 0 1-2.12-.879l-.83-.828A1 1 0 0 0 6.173 2H2.5a1 1 0 0 0-1 .981L1.546 4h-1L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3v1z"></path>
  <path fill-rule="evenodd"
        d="M13.81 4H2.19a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4zM2.19 3A2 2 0 0 0 .198 5.181l.637 7A2 2 0 0 0 2.826 14h10.348a2 2 0 0 0 1.991-1.819l.637-7A2 2 0 0 0 13.81 3H2.19z"></path>
</svg>
						         </span>
                <span class="nav-link-text">Medical Records</span>
              </a><!--//nav-link-->
            </li><!--//nav-item-->
            <li class="nav-item">
              <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
              <a class="nav-link" href="{% url 'appointments:list' %}">
						        <span class="nav-icon">
						        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd"
        d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"></path>
  <path fill-rule="evenodd"
        d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"></path>
  <circle cx="3.5" cy="5.5" r=".5"></circle>
  <circle cx="3.5" cy="8" r=".5"></circle>
  <circle cx="3.5" cy="10.5" r=".5"></circle>
</svg>
						         </span>
                <span class="nav-link-text">Appointments</span>
              </a><!--//nav-link-->
            </li><!--//nav-item-->
            <li class="nav-item">
              <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
              <a class="nav-link" href="{% url 'users:detail' user.username %}">
						        <span class="nav-icon">
						      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                       class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd"
        d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>
						         </span>
                <span class="nav-link-text">Account</span>
              </a><!--//nav-link-->
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'help' %}">
						        <span class="nav-icon">
						       <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-question-circle" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path
    d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
</svg>
						         </span>
                <span class="nav-link-text">Help</span>
              </a><!--//nav-link-->
            </li>
          </ul><!--//app-menu-->
        </nav><!--//app-nav-->
      </div><!--//sidepanel-inner-->
    </div><!--//app-sidepanel-->
  </header>

  <div class="app-wrapper">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block main_content %}
    {% endblock main_content %}
    <footer class="app-footer">
      <div class="container text-center py-3">
        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
        <small class="copyright">Designed with
          <svg class="svg-inline--fa fa-heart fa-w-16" style="color: #fb866a;" aria-hidden="true" focusable="false"
               data-prefix="fas" data-icon="heart" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
               data-fa-i2svg="">
            <path fill="currentColor"
                  d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path>
          </svg><!-- <i class="fas fa-heart" style="color: #fb866a;"></i> Font Awesome fontawesome.com --> by <a
            class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for
          developers</small>

      </div>
    </footer>
  </div>
{% endblock content %}