config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from phandler.core.views import HelpView, HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("help/", HelpView.as_view(), name="help"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("phandler.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("records/", include("phandler.records.urls", namespace="records")),
    path(
        "appointments/", include("phandler.appointments.urls", namespace="appointments")
    )
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

phandler/appointments/urls.py
from django.urls import path

from . import views

app_name = "appointments"
urlpatterns = [
    path("", views.AppointmentListView.as_view(), name="list"),
    path("create/", views.AppointmentCreateView.as_view(), name="create"),
]

phandler/records/urls.py
from django.urls import path

from . import views

app_name = "records"
urlpatterns = [
    path("doctor-create/", views.DoctorCreateView.as_view(), name="doctor_create"),
    path("patient-create/", views.PatientCreateView.as_view(), name="patient_create"),
    path("record-list/", views.RecordListView.as_view(), name="list"),
    path("record-detail/<int:pk>/", views.RecordDetailView.as_view(), name="detail"),
    path("patient-list/", views.PatientListView.as_view(), name="patient_list"),
    path("doctor-list/", views.DoctorListView.as_view(), name="doctor_list"),
]

phandler/users/urls.py
from django.urls import path

from phandler.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

phandler/appointments/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from djmoney.models.fields import MoneyField
from model_utils.models import TimeStampedModel


class Appointment(TimeStampedModel):
    record = models.ForeignKey(
        "records.Record", on_delete=models.CASCADE, related_name="history"
    )
    doctor = models.ForeignKey("records.Doctor", on_delete=models.CASCADE)
    sickness = models.CharField(max_length=255)
    prescriptions = ArrayField(models.CharField(max_length=30), default=list)
    cost = MoneyField(max_digits=14, decimal_places=2, default_currency="XOF")
    date = models.DateTimeField()
    accepted = models.BooleanField(default=True)
    duration = models.PositiveSmallIntegerField(
        default=30, help_text="Duration in minutes"
    )

    def __str__(self):
        return f"{self.record.patient} - {self.doctor} - {self.date}"

phandler/records/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel
from phonenumber_field.modelfields import PhoneNumberField


class Person(TimeStampedModel):
    class Gender(models.TextChoices):
        Male = "Male", _("Male")
        Female = "Female", _("Female")

    name = models.CharField(max_length=255)
    gender = models.CharField(choices=Gender.choices, max_length=6)
    email = models.EmailField(blank=True)
    phone = PhoneNumberField()
    id_card_number = models.CharField(max_length=30, unique=True)
    address = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Patient(Person):
    age = models.PositiveSmallIntegerField()
    allergies = ArrayField(models.CharField(max_length=30), default=list, blank=True)

    def allergies_str(self) -> str:
        return ", ".join(self.allergies)


class Doctor(Person):
    specialities = ArrayField(models.CharField(max_length=30), default=list)


class Record(TimeStampedModel):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.patient} - Medical record"

    def get_absolute_url(self) -> str:
        return reverse("records:detail", kwargs={"pk": self.pk})

phandler/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for phandler."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

phandler/appointments/forms.py
from datetime import timedelta

from django import forms

from .models import Appointment


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            "record",
            "doctor",
            "sickness",
            "prescriptions",
            "cost",
            "accepted",
            "duration",
            "date",
        ]
        widgets = {
            "date": forms.DateTimeInput(attrs={"placeholder": "DD/MM/YYYY HH:MM"})
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        date = cleaned_data["date"]
        doctor = self.cleaned_data["doctor"]
        try:
            aps = Appointment.objects.filter(doctor=doctor, date__date=date)
        except Appointment.DoesNotExist:
            pass
        else:
            for ap in aps:
                ap_end = ap.date + timedelta(minutes=ap.duration)
                if ap_end >= date:
                    raise forms.ValidationError(
                        f"Doctor {doctor} have another appointment on "
                        f"the {ap.date} for a duration of {ap.duration}"
                    )
        return cleaned_data

phandler/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

phandler/appointments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django_filters.views import FilterView
from django_tables2.export.views import ExportMixin
from django_tables2.views import SingleTableMixin

from .filters import AppointmentFilter
from .forms import AppointmentForm
from .models import Appointment
from .tables import AppointmentTable


class AppointmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = AppointmentForm
    template_name = "appointments/create.html"
    success_message = "New appointments crated"
    success_url = reverse_lazy("appointments:list")


class AppointmentListView(
    LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView
):
    queryset = Appointment.objects.all().order_by("-date")
    filterset_class = AppointmentFilter
    template_name = "appointments/list.html"
    table_class = AppointmentTable

phandler/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "pages/home.html"


class HelpView(LoginRequiredMixin, TemplateView):
    template_name = "pages/help.html"

phandler/records/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from django_filters.views import FilterView
from django_tables2.export.views import ExportMixin
from django_tables2.views import SingleTableMixin

from phandler.appointments.tables import AppointmentTable

from .filters import DoctorFilter, PatientFilter, RecordFilter
from .models import Doctor, Patient, Record
from .tables import DoctorTable, PatientTable


class PatientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Patient
    fields = [
        "name",
        "id_card_number",
        "gender",
        "age",
        "email",
        "address",
        "phone",
        "allergies",
    ]
    template_name = "records/patient_create.html"
    success_message = "Patient created"
    success_url = reverse_lazy("records:patient_list")


class DoctorCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Doctor
    fields = [
        "name",
        "id_card_number",
        "gender",
        "email",
        "address",
        "phone",
        "specialities",
    ]
    template_name = "records/doctor_create.html"
    success_message = "Doctor created"
    success_url = reverse_lazy("records:doctor_list")


class DoctorListView(LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView):
    table_class = DoctorTable
    filterset_class = DoctorFilter
    queryset = Doctor.objects.all().order_by("-created")
    template_name = "records/doctor_list.html"
    context_object_name = "doctors"


class PatientListView(LoginRequiredMixin, ExportMixin, SingleTableMixin, FilterView):
    table_class = PatientTable
    filterset_class = PatientFilter
    queryset = Patient.objects.all().order_by("-created")
    template_name = "records/patient_list.html"
    context_object_name = "patients"


class RecordListView(LoginRequiredMixin, FilterView):
    queryset = Record.objects.all().order_by("-created")
    template_name = "records/list.html"
    filterset_class = RecordFilter
    context_object_name = "records"
    paginate_by = 12


class RecordDetailView(LoginRequiredMixin, SingleTableMixin, DetailView):
    model = Record
    context_object_name = "record"
    template_name = "records/detail.html"
    table_class = AppointmentTable

    def get_table_data(self):
        return self.object.history.all().order_by("-date")

phandler/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

phandler/templates/appointments/create.html
{% extends "layouts/admin.html" %}
{% load i18n %}
{% load crispy_forms_filters %}


{% block main_content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card p-3 my-2 border-radius-xl bg-white">
          <h3>Create Appointment</h3>
          <div class="card-body">
            <div class="col-9">
              <h5 class="mb-2">
                {{ view.form_title }}
              </h5>
            </div>
            <form method="post">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn app-btn-primary" type="submit">{% trans "Submit" %}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock main_content %}

phandler/templates/appointments/list.html
{% extends "layouts/admin.html" %}
{% load render_table from django_tables2 %}
{% load i18n %}
{% load crispy_forms_filters %}


{% block main_content %}
  <div class="app-content pt-3 p-md-3 p-lg-4">
    <div class="container-xl">
      <div class="row g-3 mb-4 align-items-center justify-content-between">
        <div class="col-auto">
          <h1 class="app-page-title mb-0">Appointments</h1>
        </div>
        <div class="col-auto">
          <div class="page-utilities">
            <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
{#              <div class="col-auto">#}
{#                <form class="table-search-form row gx-1 align-items-center" action="." method="get" >#}
{#                  <div class="col-auto">#}
{#                      <input type="text" id="id_name" name="name" class="form-control search-orders" placeholder="Name">#}
{#                  </div>#}
{#                  <div class="col-auto">#}
{#                    <button type="submit" class="btn app-btn-secondary">Search</button>#}
{#                  </div>#}
{#                </form>#}
{##}
{#              </div>#}
              <div class="col-auto">

                <a class="btn app-btn-primary" href="{% url 'appointments:create' %}">New Appointment</a>
              </div>
              <div class="col-auto">
                <a class="btn app-btn-secondary" href="{% url 'appointments:list' %}?_export=csv">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download me-1" fill="currentColor"
                       xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"></path>
                    <path fill-rule="evenodd"
                          d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"></path>
                  </svg>
                  Download CSV
                </a>
              </div>
            </div><!--//row-->
          </div><!--//table-utilities-->
        </div><!--//col-auto-->
      </div><!--//row-->

      <div class="app-card app-card-orders-table shadow-sm mb-5">
        <div class="app-card-body">
          <div class="table-responsive">
            {% render_table table %}
          </div><!--//table-responsive-->

        </div><!--//app-card-body-->
      </div>
    </div><!--//container-fluid-->
  </div>
{% endblock main_content %}